"""
src/cbs/annotation.py — CBS-tier + cross-domain sentence annotator.

Purpose
-------
Second-pass annotation over Phase-3 behaviour-labelled sentences, assigning
each `adding-knowledge` / `deduction` sentence:

  * a CBS tier in {1 retrieval, 2 recombination, 3 novel application},
  * a `knowledge_domain` label,
  * a binary `cross_domain` flag,
  * a one-sentence rationale and an explicit confidence.

Inputs / Outputs
----------------
Inputs:
  * Phase 3 annotated chains  (`data/annotated_R1-1.5B.json`)
  * Sonnet 4.5 client         (proxy; see `src/annotation.py` for transport)

Outputs:
  * `data/chains_cbs_annotated_R1-1.5B.json` (Phase 3 + CBS fields)
  * Optional `results/cbs/{model}/kappa_run1_run2.json` under `--dual-seed-kappa`

Validation
----------
P0.2 pilot pass criteria (synthesis §P0.2):
  * Cohen's kappa >= 0.5
  * human-vs-Sonnet >= 70%
  * tier-3 rate >= 5%

Fail-stop on any criterion failure; write
`results/cbs/{model}/FAILSTOP_M1.md` with three options for the user.

Milestone
---------
M1 (synthesis §M1.1–§M1.5). P0.3 lays down the skeleton.
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Optional, Protocol

from src.cbs.schemas import CBSResult, TASK_DOMAINS

logger = logging.getLogger(__name__)


# The locked CBS prompt template. Anchors are filled in only AFTER P0.2
# anchor curation completes. Until then the placeholder is used and results
# are tagged `pilot-only`.

CBS_PROMPT_TEMPLATE: str = """\
You are annotating a single sentence from a mathematical reasoning chain
generated by a language model. The sentence has already been classified
under a behaviour label (typically "adding-knowledge" or "deduction").

Your task: assign a CONTENT-BEYOND-SOURCE TIER from {{1, 2, 3}} indicating
how much novel content this sentence carries relative to standard
techniques for the problem's home domain. ALSO assign a knowledge_domain
label and a binary cross_domain flag.

TIER DEFINITIONS:

Tier 1 - RETRIEVAL.
  A single fact, formula, or definition directly stated in standard
  textbook coverage of the problem's home domain. No combination of facts;
  no new application.

Tier 2 - RECOMBINATION.
  Combines facts from two or more sources, but the combination is a
  standard textbook move for problems of this type.

Tier 3 - NOVEL APPLICATION.
  Invokes a technique that is not standard for the problem's home domain
  - for example, using a number-theoretic identity to bound a geometric
  quantity, or applying a generating-function argument to a graph problem.

ANCHOR EXAMPLES (drawn from this corpus):
{anchor_block}

KNOWLEDGE_DOMAIN LABELS:
{{algebra, geometry, number_theory, combinatorics, calculus, probability,
 logic, other}}

PROBLEM HOME DOMAIN: {task_domain}
PROBLEM STATEMENT: {task_prompt}
CONTEXT (previous 3 sentences):
{prev_sentences}

SENTENCE TO CLASSIFY (behaviour label: {behaviour}):
{sentence}

Respond as JSON only, no preamble:
{{
  "tier": 1 | 2 | 3,
  "knowledge_domain": "<one of the labels above>",
  "cross_domain": true | false,
  "rationale": "<one sentence, max 30 words>",
  "confidence": "high" | "medium" | "low"
}}
"""


PLACEHOLDER_ANCHOR_BLOCK: str = (
    "  [PILOT-ONLY PLACEHOLDER ANCHORS - pipeline runs are pilot-only until\n"
    "   results/cbs/anchor_candidates.csv is curated by Tony and the locked\n"
    "   anchor block is substituted in here.]\n"
)


class SonnetClient(Protocol):
    """Minimal protocol any client must satisfy.

    Implementations return the raw assistant-message string. Annotation code
    parses the JSON itself so the client need not be JSON-aware.
    """

    def complete(self, prompt: str, *, seed: int, temperature: float) -> str:
        ...


def annotate_task_domain(task: dict, client: SonnetClient) -> str:
    """One-shot Sonnet call to classify a task's home domain.

    Returns one of `TASK_DOMAINS`. Caller should cache by `task["id"]`.
    """
    raise NotImplementedError("Filled in at M1 (synthesis §M1.3).")


def annotate_sentence_cbs(
    sentence: str,
    behaviour: str,
    task_domain: str,
    task_prompt: str,
    prev_sentences: list[str],
    client: SonnetClient,
    seed: int = 0,
    anchor_block: str = PLACEHOLDER_ANCHOR_BLOCK,
) -> CBSResult:
    """Annotate one sentence; returns a CBSResult.

    Raises on malformed model output; callers handle retries.
    """
    raise NotImplementedError("Filled in at M1 (synthesis §M1.3).")


def annotate_chains_cbs(
    annotated_chains: list[dict],
    client: SonnetClient,
    *,
    seed: int = 0,
    max_workers: int = 8,
    anchor_block: str = PLACEHOLDER_ANCHOR_BLOCK,
    task_domain_cache: Optional[dict[str, str]] = None,
) -> list[dict]:
    """Add `cbs_*` fields to every sentence with behaviour in
    {adding-knowledge, deduction}; pass other sentences through unchanged."""
    raise NotImplementedError("Filled in at M1 (synthesis §M1.3).")


def build_anchor_candidates_csv(
    annotated_chains_path: Path,
    out_csv: Path,
    *,
    n_per_category: int = 6,
    behaviours: tuple[str, ...] = ("adding-knowledge", "deduction"),
    seed: int = 0,
) -> Path:
    """Sample ~60 sentences stratified by task category for human anchor
    curation (P0.2). Returns the output path."""
    raise NotImplementedError("Filled in at M1 / P0.2 (synthesis §P0.2).")
